# Generated by Django 3.0.3 on 2020-08-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shared',
        ),
    ]
