# Generated by Django 3.0.3 on 2020-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicts', models.CharField(max_length=120000000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicts', models.CharField(max_length=120000000000000)),
                ('hawla_KI', models.CharField(max_length=120000000000000)),
            ],
        ),
    ]
